### ISSUE TITLE
您好，我想做一个类似的校园交友小程序，请问加个联系方式可以交流一下么~

### ISSUE THREAD

**Issue by Palmer-C** [vivid05/wxapp#1]

**Comment by vivid05** [comment]
微信: 15605951630------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月15日(星期四) 上午9:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[vivid05/wxapp] 您好，我想做一个类似的校园交友小程序，请问加个联系方式可以交流一下么~ (#1)

**Comment by vivid05** [comment]
835515480
